server:
  port: 8848
  servlet:
    context-path: /api
    session:
      cookie:
        domain:
spring:
  application:
    name: voiceLink-guardian-backend
  profiles:
    active: dev
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shenglian_guardian
    username: root
    password: 123456

  # session 失效时间(分钟)，一天86400s
  session:
    timeout: 86400

  # Spring Boot 2.6.x整合Swagger启动失败报错，默认匹配策略是 path-pattern-matcher
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
    # 仅在开发环境的打印日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      # 逻辑删除配置
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1         # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0     # 逻辑未删除值（默认为 0）

# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: 深联守护接口文档
    description: "`我是测试`,**你知道吗**
    # aaa"
    email: 16608683257@163.com
    concat: Qiu Ping
    url: https://github.com/qiuping01
    version: v1.0
    license: Apache 1.0
    group:
      default:
        group-name: 默认分组
        api-rule: package
        api-rule-resources:
          - com.ping.voicelinkguardianbackend.cotroller